# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "/go/bin/main"
  cmd = "go build -o /go/bin/main -buildvcs=false ./cmd"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["vendor", "storage", "tmp", "haproxy"]
  exclude_file = ["haproxy.cfg", "haproxy/haproxy.cfg"]
  follow_symlink = true
  delay = 1000
  poll = true
  log = "build.log"

[log]
  time = true
  level = "debug"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"